Story/37856
prefeiturasp/SME-ServidorRelatorios pull request #2458
Opened 2023-02-17 14:51 UTC by Jailsvs

AB#37856
AB#86851

2023-02-17 15:00 UTC, DanylloAntunes approved these changes

2023-02-17 17:53 UTC, rafalosiamcom requested changes

2023-02-17 17:53 UTC, rafalosiamcom commented on src/SME.SR.Application/Queries/Professor/ObterProfessorTitularExternoComponenteCurricularPorTurma/ObterProfessorTitularExternoComponenteCurricularPorTurmaQueryHandler.cs
> +            return lstProfessores;
```suggestion
        public Task<IEnumerable<ProfessorTitularComponenteCurricularDto>> Handle(ObterProfessorTitularExternoComponenteCurricularPorTurmaQuery request, CancellationToken cancellationToken)
        {
            return professorRepository.BuscarProfessorTitularExternoComponenteCurricularPorTurma(request.CodigosTurma);
```

2023-02-17 17:53 UTC, rafalosiamcom commented on src/SME.SR.Data/Repositories/Eol/ProfessorRepository.cs
> +                                       and atb_ext_prog.an_atribuicao = year(getdate())
vai buscar sempre atribuição do ano atual mesmo ?
o que ocorre se emitir o relatório para turma histórica ?

2023-02-17 17:53 UTC, rafalosiamcom commented on src/SME.SR.Data/Repositories/Eol/ProfessorRepository.cs
> +            var parametros = new { codigosTurma };
temos que começar a usar o parametro DBChar assim como implementamos na API EOL para essas queries do EOL

2023-02-17 18:29 UTC, Jailsvs commented on src/SME.SR.Data/Repositories/Eol/ProfessorRepository.cs
> +                                       and atb_ext_prog.an_atribuicao = year(getdate())
Este item teremos que avaliar com Marlon, pois a busca de professores da turma com atribuição aula (já existente para o mesmo relatório), somente utiliza ano atual.... E faz sentido apresentar no campo o padrão atual "Não existe professor para a turma" em caso de histórico - é o que faz atualmente

2023-02-17 18:29 UTC, Jailsvs commented on src/SME.SR.Application/Queries/Professor/ObterProfessorTitularExternoComponenteCurricularPorTurma/ObterProfessorTitularExternoComponenteCurricularPorTurmaQueryHandler.cs
> +            return lstProfessores;
Feito

2023-02-17 18:39 UTC, Jailsvs commented on src/SME.SR.Data/Repositories/Eol/ProfessorRepository.cs
> +            var parametros = new { codigosTurma };
Adicionei o dapper constants com tamanho nas queries que ja utilizavam o ToDbChar, porém, neste caso se trata de um campo numérico (int) e não necessitaria do tratamento.

2023-02-20 11:05 UTC, rafalosiamcom approved these changes

2023-02-20 11:05 UTC, merged