99365 - Saindo estudantes que ficaram inativos antes do começo do ano
prefeiturasp/SME-ServidorRelatorios pull request #2892
Opened 2023-07-18 17:51 UTC by DanylloAntunes

AB#99365

2023-07-21 10:58 UTC, Jailsvs approved these changes

2023-07-21 12:47 UTC, rafalosiamcom requested changes

2023-07-21 12:47 UTC, rafalosiamcom commented on src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
> +            .Where(a => a.Inativo && a.DataSituacaoAluno.Date >= periodoEscolar.PeriodoInicio)
Não deveria ser entre Inicio e Fim ?

2023-07-21 18:48 UTC, rafalosiamcom approved these changes

2023-07-21 18:48 UTC, merged

2023-08-28 13:59 UTC, rafalosiamcom commented on src/SME.SR.Application/Queries/RelatorioConselhoClasseAtaBimestral/ObterRelatorioConselhoClasseAtaBimestralPdf/ObterRelatorioConselhoClasseAtaBimestralPdfQueryHandler.cs
> +            .Where(a => a.Inativo && a.DataSituacaoAluno.Date >= periodoEscolar.PeriodoInicio)
alinhado com o desenvolvedor