Story/102517
prefeiturasp/SME-ServidorRelatorios pull request #3289
Opened 2024-02-26 17:15 UTC by DanylloAntunes

AB#102517
AB#115485

2024-02-26 18:16 UTC, Jailsvs approved these changes

2024-02-27 14:11 UTC, rafalosiamcom requested changes

2024-02-27 14:11 UTC, rafalosiamcom commented on src/SME.SR.Data/Repositories/Sgp/EncaminhamentoNAAPARespostaRepository.cs
> +                          and nome_componente = ANY(@componentes)";
filtrar resposta not excluido

2024-02-27 14:11 UTC, rafalosiamcom commented on src/SME.SR.Infra/Armazenamento/ServicoArmazenamento.cs
> +        public string Obter(string nomeArquivo, bool ehPastaTemp)
no SR não faz sentido ter arquivo na pasta temp, pode remover essa opção

2024-02-27 16:45 UTC, rafalosiamcom approved these changes

2024-02-27 16:46 UTC, merged